### ISSUE TITLE
[UI] 스코어 보드

### ISSUE THREAD

**Issue by isTest001** [wise1ight/tetris#27]
게임의 역대 점수 순위를 보여주는 스코어 보드를 구현.

• 각 순위별로 이름 및 점수 등의 정보를 점수가 높은 순으로 정렬하여 보여줌.

• 전체 기록된 순위는 적어도 상위 10개 이상을 포함.

• 설정에서 초기화하기 전에는 프로그램을 종료하더라도 스코어 보드 기록이 유지되어야 함.

• 그 외의 사항은 자유롭게 설계 및 구현.

+게임 종료시의 스코어 보드에는 현재점수 강조 혹은 애니메이션

**Comment by wise1ight** [comment]
구현 완료로 인한 종료
