### ISSUE TITLE
[Logic] 블럭

### ISSUE THREAD

**Issue by wlsh44** [wise1ight/tetris#4]
• 참조 코드에 제시된 7가지 모양의 블럭을 구현.

• https://github.com/Jindae/SeoulTech-SE-Tetris-Ref

• 다음에 나타날 블럭은 동일한 확률로 무작위로 결정됨.

• 각각의 블럭은 모두 다른 색상을 가져야 함.

•  **유사한 모양이나 좌우가 바뀐 블럭들은 구분이 용이하도록 대비되는 색상이나 무늬를 지녀야 함**

**Comment by wise1ight** [comment]
머지 완료

**Comment by wise1ight** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Logic] 블럭](https://trello.com/c/tQOcdDLj/46-logic-%EB%B8%94%EB%9F%AD)
