### ISSUE TITLE
[Logic] 게임 보드 및 조작

### ISSUE THREAD

**Issue by wlsh44** [wise1ight/tetris#6]
• 텍스트 기반 보드 만들어야 함. (가로 10, 세로 20)

• 보드에 현재 블럭이 생성되면, 이 블럭은 아무 조작이 없어도 1초에 1칸씩 밑으로 떨어져야 함.

• 일정 수 이상의 블럭이 생성되거나, 줄이 삭제되면 떨어지는 속도가 증가해야 함.

• 현재 블럭을 키보드 입력에 따라 다음과 같이 조작 가능해야 함.

• 좌, 우, 아래로 한 칸씩 이동시킬 수 있어야 함. **(←, ↓, →)**

• 시계방향으로 90도씩 회전시킬 수 있어야 함.

• 한 번에 끝까지 밑으로 떨어뜨릴 수 있어야 함. **(Space)**

• 반복된 키 입력이 무시되지 않고 블럭이 즉시, 정확하게 반응해야 함.

• 게임 도중 게임을 잠시 중단/재개할 수 있는 키가 존재해야 함. **(P, ESC)**

• 게임 진행/중지 상태에서 게임을 종료할 수 있는 방법이 존재해야 함 (alt-f4 등 OS를 이용한 방법 제외)

**Comment by wlsh44** [comment]
- [x] 텍스트 기반 보드 만들어야 함. (가로 10, 세로 20)

- [x] 보드에 현재 블럭이 생성되면, 이 블럭은 아무 조작이 없어도 1초에 1칸씩 밑으로 떨어져야 함.

- [x] 좌, 우, 아래로 한 칸씩 이동시킬 수 있어야 함. **(←, ↓, →)**

- [x] 시계방향으로 90도씩 회전시킬 수 있어야 함.

- [x] 한 번에 끝까지 밑으로 떨어뜨릴 수 있어야 함. **(Space)**

- [x] 반복된 키 입력이 무시되지 않고 블럭이 즉시, 정확하게 반응해야 함.

- [ ] 일정 수 이상의 블럭이 생성되거나, 줄이 삭제되면 떨어지는 속도가 증가해야 함.

- [ ] 게임 도중 게임을 잠시 중단/재개할 수 있는 키가 존재해야 함. **(P, ESC)**

- [ ] 게임 진행/중지 상태에서 게임을 종료할 수 있는 방법이 존재해야 함 (alt-f4 등 OS를 이용한 방법 제외)

**Comment by wise1ight** [comment]
Swing 부분 보완 후 남은 작업 진행 예정.

**Comment by wise1ight** [comment]
담당자 추가 @wise1ight
