### ISSUE TITLE
[Logic] 일반 대전 모드

### ISSUE THREAD

**Issue by seong0929** [wise1ight/tetris#64]
상대방에게 넘어간 블럭은 상대방 보드의 아래쪽으로 넘어간 형태 그대로 추가됩니다.

- 직접 쌓은 블럭과 구분하기 위해 추가된 블럭은 회색으로 처리합니다.
- 색상은 자유롭게 결정해도 무방합니다.
- 기본 게임과 마찬가지로 플레이어 중 어느 한 쪽이 더 이상 블럭을 쌓을 수 없게 되면 게임이 종료됩니다.
- 대전 모드에서는 한 플레이어가 더 이상 블럭을 쌓지 못하는 상태가 되면, 다른 플레이어가 승자가 됩니다.

- 상대 플레이어에게 넘길 수 있는 최대 줄 수는 10줄입니다.
- 여러 번의 공격으로 추가되는 줄은 현재 넘어간 줄의 아래쪽으로 추가됩니다.
- 추가될 줄이 표시되는 부분에 이미 10줄이 차 있는 경우, 줄을 삭제해도 상대방에게 넘어가지 않고 무시됩니다.
- 현재 10줄이 다 차있지 않더라도 넘어온 줄의 수를 더하여 10줄이 넘게 된다면, 제일 아래쪽 부분을 잘라내고 추가합니다

**Comment by wlsh44** [comment]
- [ ] 줄 지웠을 때 넘길 라인 저장하는 기능
- [ ] 줄 아래쪽에 추가하는 기능
- [ ] 10줄이 차 있을 경우 저장x
- [ ] 넘어온 줄 + 기존 줄 > 10일 경우 맨 아래쪽 부분 삭제하고 추가
- [ ] 게임 승패 부분
