### ISSUE TITLE
[UI] 설정 화면

### ISSUE THREAD

**Issue by wise1ight** [wise1ight/tetris#8]
• 설정 화면에서는 다음과 같은 기능을 제공해야 함.

• 테트리스 게임 화면의 크기를 조절 - 최소 3가지 이상 미리 정의된 크기.

• 게임 조작을 위해 사용될 키를 설정.

• 스코어 보드의 기록을 초기화.

• 색맹 모드 켜고 끄기.

• 모든 설정으로 기본 설정으로 되돌리기.

• 바뀐 설정은 저장되었다가 다음 게임 실행시 동일한 설정을 불러와 사용할 수 있어야 함.

• 그 밖의 필요한 설정을 추가하는 것도 가능.

Java의 Preferences API를 활용하여 개발할 예정임.

**Comment by wise1ight** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[UI] 설정 화면](https://trello.com/c/LWGLyEmK/49-ui-%EC%84%A4%EC%A0%95-%ED%99%94%EB%A9%B4)

**Comment by wise1ight** [comment]
UI는 만듬

**Comment by wlsh44** [comment]
- [ ] 난이도 설정

**Comment by wise1ight** [comment]
- [x] 누락된 키 설정 부분 추가

**Comment by wise1ight** [comment]
UI 구현 완료
