### ISSUE TITLE
[UI] 테트리스 화면 구성

### ISSUE THREAD

**Issue by isTest001** [wise1ight/tetris#9]
• 기본적인 화면 구성은 다음을 포함.

• 블럭이 쌓이는 보드(board), 다음 블럭을 확인할 수 있는 부분, 점수를 확인할 수 있는 부분.

• 보드는 블럭의 한 칸을 기준으로 하였을 때 20개의 줄과 10개의 칸을 가져야 함.

• 다음 블럭 부분은 각 블럭이 보드에 생성될 때마다 다음에 생성될 블럭들을 표시.

• 점수 부분은 실시간으로 바뀌는 점수를 표시

**Comment by wise1ight** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[UI] 테트리스 화면 구성](https://trello.com/c/DLJWz7EG/45-ui-%ED%85%8C%ED%8A%B8%EB%A6%AC%EC%8A%A4-%ED%99%94%EB%A9%B4-%EA%B5%AC%EC%84%B1)
